name: permut
version: 1.03
date: 30/07/2015
description: |
    A package to deal with permutability in finite groups

authors:
    - name: Adolfo Ballester-Bolinches
      url: mailto:Adolfo.Ballester@uv.es
    - name: Enric Cosme-Ll\'opez
      url: http://www.uv.es/coslloen
    - name: Ram\'on Esteban-Romero
      url: http://www.uv.es/estebanr

maintainers:
    - name: Ram\'on Esteban-Romero
      url: http://www.uv.es/estebanr

GAP: "4.7.4"

needed-pkgs:
    - name: "format"
      version: "1.3"
      url: "http://www.uoregon.edu/~wright/RESEARCH/format/"

www: http://www.uv.es/permut/gap/permut-1.03/
readme: README.permut
packageinfo: http://www.uv.es/permut/gap/permut/PackageInfo.g

downloads:
    - name: .tar.bz2
      url: http://www.uv.es/permut/gap/permut-1.03/permut-1.03.tar.bz2

abstract: |
    This package provides functions for computing with permutability in finite groups.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
